apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ArgoApp
  namespace: dev
spec:
  project: default
  source:
    repoURL: 'https://github.com/mathis54300/Kubernetes.git'
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
